name: goreleaser

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Make All
        run: |
          ./package.sh
          pwd
          ls -l /home/runner/work/frp/frp/release/
          ls -l /home/runner/work/frp/frp/release/packages    
      
      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Padavan-packages
          path: /opt/images

      
