name: goreleaser

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Clone source code
        run: | 
          go get github.com/fatedier/frp
          pwd
        

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Make All
        run: |
          ./package.sh
          pwd
          ls /home/runner/work/frp/frp/release
#mkdir -p /opt/images/
#sudo mv -f release/frpc_linux_mipsle /opt/images/ 
      
      - name : Upload frp
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Frp-packages
          path: /home/runner/work/frp/frp/release

      
